id: PDA457B13
initial_creation_type: ocr
source_metadata:
  volumes:
    b88750617bb34ed589e41bb716b1863a:
      base_file: v061.txt
      image_group_id: I1PD96844
      title: འཕགས་པ་བྱམས་པ་འཇུག་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 872
      volume_number: 61
vol2fn:
  v061: v061.txt
